model-name: case-study
technology-instances:
  kubernetes:
    sock-shop:
      kube-config-path: C:/Users/lharz/.kube/config
      target-namespace: sock-shop
      ignored-container-names:
        - "queue-master"
        - "rabbitmq"
        - "rabbitmq-exporter"
        - "session-db"
        - "payment"
        - "shipping"
        - "user"
        - "user-db"
  puppet:
    catalogue:
      user: ubuntu
      ip: 193.196.53.189
      private-key-path: C:/Users/lharz/.ssh/BWCloud.pem
      environment: production
  terraform:
   desktop-local:
     state-file: C:/git-repos/lharzenetter/multi-deployment-technologies-example/puppet-agent-setup/openstack/terraform.tfstate

